version: '2'
services:
  sqldata:
    image: busybox
    volumes:
      - ./data/mysql:/var/lib/mysql
  wwwdata:
    image: busybox
    volumes:
      - ./data/www:/var/www/html
  nginx: 
    build: ./nginx
    ports: 
      - "80:80"
    links: 
      - php7
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/server.conf
    volumes_from:
      - wwwdata
  php7: 
    build: ./php7
    links: 
      - db
    volumes:
      - ./php7/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
      - wwwdata
    depends_on:
      - "db"
  db:
    image: mysql
    volumes_from:
      - sqldata
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      TZ: "Asia/Tokyo"
